language: java
before_install:
  - sudo add-apt-repository ppa:linuxuprising/java
  - sudo apt-get update
  - sudo apt-get install oracle-java10-installer
cache:
  directories:
    - $HOME/.gradle
script:
  - ./gradlew clean build
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
