language: java
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
matrix:
  include:
    - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL -C
cache:
  directories:
    - $HOME/.gradle
script:
  - ./gradlew clean build
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
